# Generated by Django 6.0.3 on 2026-03-22 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appCombustibles', '0001_initial'),
        ('appUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cisterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_combustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCombustibles.combustible')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appUsuarios.usuario')),
            ],
        ),
    ]
