# Generated by Django 6.0.3 on 2026-03-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, unique=True)),
                ('precio_por_litro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
