# Generated by Django 6.0.3 on 2026-03-22 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appClientes', '0001_initial'),
        ('appCombustibles', '0001_initial'),
        ('appUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_bs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appClientes.cliente')),
                ('combustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCombustibles.combustible')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appUsuarios.user')),
            ],
        ),
    ]
